<!DOCTYPE html>
<html lang="hu">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

    <title>WMF</title>

    <meta name="description" content="I wouldn't waste 2 minutes optimising my keyword meta tags for Google, but Google tells us to pay attention to meta descriptions.">
    <meta name="keywords" content="SEO, search engine optimisation, optimization">

    <!-- Favicons -->

    <!-- Screen CSS -->
    <link href="<?php echo $this->config->rootDir; ?>/<?php echo $this->system; ?>/view/<?php echo $this->config->template; ?>/css/screen.css?t=<?php echo time(); ?>" rel="stylesheet">

    <!-- 3rd-party CSS files -->

    <!-- JQuery -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>

    <!-- 3rd-party JS files -->

    <!-- Main JS file -->
    <script src="<?php echo $this->config->rootDir; ?>/<?php echo $this->system; ?>/view/<?php echo $this->config->template; ?>/js/main.js?t=<?php echo time(); ?>"></script>

    <!-- WMF Ready -->
    <script>
        var wmf;
        $(document).ready(function() {
            wmf = new Wmf();
        });
    </script>

    <!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
    <script>
        (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
        function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
        e=o.createElement(i);r=o.getElementsByTagName(i)[0];
        e.src='https://www.google-analytics.com/analytics.js';
        r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
        ga('create','UA-XXXXX-X','auto');ga('send','pageview');
    </script>
</head>
<body>
<!--[if lt IE 9]>
    <p class="browserupgrade"><strong>Elavult</strong> böngészőt használsz. Kérlek <a href="http://browsehappy.com/">tölts le</a> újabb böngészőt, az optimális böngészés érdekében.</p>
<![endif]-->
